# ═══════════════════════════════════════════════
# Oracle AIDP Migrated Notebook
# Generated by DB→AIDP Migration Studio
# ═══════════════════════════════════════════════

# ── Cell [1] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# Databricks notebook source
# MAGIC %sql
# MAGIC
# MAGIC
# MAGIC create external volume if not exists deltalake.silver.chekcpoint
# MAGIC location 'abfss://fakerstream@dbstorageext01.dfs.core.windows.net/silver/checkpo'
# MAGIC comment 'silverloaction ';

# ── Cell [2] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# COMMAND ----------

df_bronze = spark.readStream.format("delta") \
    .load("/Volumes/deltalake/bronze/rawinbound")

# ── Cell [3] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# COMMAND ----------

from pyspark.sql.functions import col

df_clean = (
    df_bronze
    .filter(col("event_id").isNotNull())
    .withColumn("event_time", col("event_time").cast("timestamp"))
    .filter(col("event_time").isNotNull())
)

# ── Cell [4] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# COMMAND ----------

df_watermarked = df_clean.withWatermark("event_time", "10 minutes")

# ── Cell [5] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# COMMAND ----------

df_dedup = df_watermarked.dropDuplicates(["event_id"])

# ── Cell [6] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# COMMAND ----------

from pyspark.sql.functions import current_timestamp

df_enriched = df_dedup.withColumn("processed_time", current_timestamp())

# ── Cell [7] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# COMMAND ----------

# ── Cell [8] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# COMMAND ----------

query_silver = (
    df_enriched.writeStream
    .format("delta")
    .option("checkpointLocation", "/Volumes/deltalake/silver/chekcpoint")
    .outputMode("append")
    .toTable("deltalake.silver.orders")
)

# ── Cell [9] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE deltalake.silver.orders
# MAGIC USING DELTA
# MAGIC LOCATION 'abfss://fakerstream@dbstorageext01.dfs.core.windows.net/silver/data';
# MAGIC
# MAGIC [RequestId=fed0e114-2f89-48bb-adca-454f9ea5bf65 ErrorClass=INVALID_PARAMETER_VALUE] Unsupported path operation PATH_CREATE_TABLE on volume

# ── Cell [10] ──────────────────────────────────────
# ⚠ NOT MIGRATED — original preserved
# COMMAND ----------

# MAGIC %sql
# MAGIC select * from deltalake.silver.orders;
# MAGIC

